targets:
  $default:
    sources:
      - integration_test/**
      - test/**
      - lib/**
      - web/**
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # auto registers any class with a name matches the given pattern
          class_name_pattern:
            "^.*UseCase$|^.*Mapper$|^.*RepositoryImpl$|^.*DataSource$"
          # auto registers any class inside a file with a
          # name matches the given pattern
          # file_name_pattern: "_bloc$|_use_case$|_data_source$|_mapper"
      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/**/*.dart
      mockito:mockBuilder:
        generate_for:
          - test/**/*.dart
          - integration_test/**.dart
          - integration_test/**/*.dart
      json_serializable:json_serializable:
        generate_for:
          - lib/**/*.dart