name: polygonid_flutter_sdk
description: PolygonID Flutter SDK (https://polygon.technology/polygon-id). This plugin provides a cross-platform tool (iOS, Android) to integrate the PolygonID solution.
version: 2.4.0
homepage: https://polygon.technology/polygon-id
repository: https://github.com/0xPolygonID/polygonid-flutter-sdk
issue_tracker: https://github.com/0xPolygonID/polygonid-flutter-sdk/issues
documentation: https://0xpolygonid.github.io/tutorials/

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  http: ">=1.0.0"
  dio: ^5.4.3+1
  dio_cache_interceptor: ^4.0.0
  http_cache_hive_store: ^5.0.0

  # Web3
  web3dart: ^2.7.3

  # Crypto
  crypto: ^3.0.1
  pointycastle: ^4.0.0
  ninja_prime: ^2.0.0
  ed25519_edwards: ^0.3.1
  secp256k1: ^0.3.0
  poseidon: ^0.0.1
  jose_plus:
    path: packages/jose

  # ZK proof
  flutter_rapidsnark: 0.0.1-beta.4
  circom_witnesscalc: 0.0.1-alpha.4

  # FFI
  ffi: ^2.1.2

  # DI
  get_it: ^8.2.0
  injectable: ^2.5.1

  # Storage
  sembast: ^3.8.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  hex: ^0.2.0
  uuid: ^4.0.0
  json_annotation: ^4.6.0
  equatable: ^2.0.7
  path_provider: ^2.0.15
  archive: ^4.0.7
  package_info_plus: ">=7.0.0"
  logger: ^2.0.1
  intl: ">=0.18.1"
  background_downloader: ^9.2.3
  meta: ^1.15.0
  md5_file_checksum: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: 6.11.1
  injectable_generator: ^2.8.1
  build_runner: ^2.7.0
  ffigen: ^19.1.0
  mockito: ^5.3.2

dependency_overrides:
  pointycastle: 4.0.0

ffigen:
  # dart run ffigen

  name: NativePolygonIdCoreLib
  description: Bindings to `ios/Classes/libpolygonid.h`.
  output: 'lib/common/libs/polygonidcore/native_polygonidcore.dart'
  headers:
    entry-points:
      - 'ios/polygonid_flutter_sdk/Frameworks/libpolygonid.xcframework/libpolygonid.h'
  functions:
    include:
      - PLGN.*
  structs:
    include:
      - PLGN.*
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, unused_local_variable
  compiler-opts-automatic:
    macos:
      include-c-standard-library: true

flutter:
  plugin:
    platforms:
      android:
        package: io.iden3.polygonid_flutter_sdk
        pluginClass: PolygonIdSdkPlugin
      ios:
        pluginClass: PolygonIdSdkPlugin

  assets:
    - lib/assets/
