// Mocks generated by Mockito 5.3.2 from annotations
// in polygonid_flutter_sdk/test/domain/use_cases/get_jwz_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:polygonid_flutter_sdk/common/domain/entities/filter_entity.dart'
    as _i10;
import 'package:polygonid_flutter_sdk/credential/domain/entities/claim_entity.dart'
    as _i8;
import 'package:polygonid_flutter_sdk/iden3comm/domain/entities/proof_request_entity.dart'
    as _i11;
import 'package:polygonid_flutter_sdk/iden3comm/domain/entities/request/auth/proof_scope_request.dart'
    as _i9;
import 'package:polygonid_flutter_sdk/proof/domain/entities/circuit_data_entity.dart'
    as _i2;
import 'package:polygonid_flutter_sdk/proof/domain/entities/gist_proof_entity.dart'
    as _i4;
import 'package:polygonid_flutter_sdk/proof/domain/entities/jwz/jwz.dart'
    as _i12;
import 'package:polygonid_flutter_sdk/proof/domain/entities/jwz/jwz_proof.dart'
    as _i3;
import 'package:polygonid_flutter_sdk/proof/domain/repositories/proof_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCircuitDataEntity_0 extends _i1.SmartFake
    implements _i2.CircuitDataEntity {
  _FakeCircuitDataEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJWZProof_1 extends _i1.SmartFake implements _i3.JWZProof {
  _FakeJWZProof_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGistProofEntity_2 extends _i1.SmartFake
    implements _i4.GistProofEntity {
  _FakeGistProofEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProofRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProofRepository extends _i1.Mock implements _i5.ProofRepository {
  MockProofRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> isCircuitSupported({required String? circuitId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCircuitSupported,
          [],
          {#circuitId: circuitId},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<_i2.CircuitDataEntity> loadCircuitFiles(String? circuitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCircuitFiles,
          [circuitId],
        ),
        returnValue:
            _i6.Future<_i2.CircuitDataEntity>.value(_FakeCircuitDataEntity_0(
          this,
          Invocation.method(
            #loadCircuitFiles,
            [circuitId],
          ),
        )),
      ) as _i6.Future<_i2.CircuitDataEntity>);
  @override
  _i6.Future<_i7.Uint8List> calculateAtomicQueryInputs(
    String? id,
    int? profileNonce,
    int? claimSubjectProfileNonce,
    _i8.ClaimEntity? claim,
    _i9.ProofScopeRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateAtomicQueryInputs,
          [
            id,
            profileNonce,
            claimSubjectProfileNonce,
            claim,
            request,
          ],
        ),
        returnValue: _i6.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i6.Future<_i7.Uint8List>);
  @override
  _i6.Future<_i7.Uint8List> calculateWitness(
    _i2.CircuitDataEntity? circuitData,
    _i7.Uint8List? atomicQueryInputs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateWitness,
          [
            circuitData,
            atomicQueryInputs,
          ],
        ),
        returnValue: _i6.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i6.Future<_i7.Uint8List>);
  @override
  _i6.Future<_i3.JWZProof> prove(
    _i2.CircuitDataEntity? circuitData,
    _i7.Uint8List? wtnsBytes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #prove,
          [
            circuitData,
            wtnsBytes,
          ],
        ),
        returnValue: _i6.Future<_i3.JWZProof>.value(_FakeJWZProof_1(
          this,
          Invocation.method(
            #prove,
            [
              circuitData,
              wtnsBytes,
            ],
          ),
        )),
      ) as _i6.Future<_i3.JWZProof>);
  @override
  _i6.Future<List<_i10.FilterEntity>> getFilters(
          {required _i11.ProofRequestEntity? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilters,
          [],
          {#request: request},
        ),
        returnValue:
            _i6.Future<List<_i10.FilterEntity>>.value(<_i10.FilterEntity>[]),
      ) as _i6.Future<List<_i10.FilterEntity>>);
  @override
  _i6.Future<String> encodeJWZ({required _i12.JWZEntity? jwz}) =>
      (super.noSuchMethod(
        Invocation.method(
          #encodeJWZ,
          [],
          {#jwz: jwz},
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<_i4.GistProofEntity> getGistProof({
    required String? idAsInt,
    required String? contractAddress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGistProof,
          [],
          {
            #idAsInt: idAsInt,
            #contractAddress: contractAddress,
          },
        ),
        returnValue:
            _i6.Future<_i4.GistProofEntity>.value(_FakeGistProofEntity_2(
          this,
          Invocation.method(
            #getGistProof,
            [],
            {
              #idAsInt: idAsInt,
              #contractAddress: contractAddress,
            },
          ),
        )),
      ) as _i6.Future<_i4.GistProofEntity>);
}
